Implement flask backend, streamlit frontend, and telegram bot frontend
AzimMuradov/mini-oracle pull request #1
Opened 2022-12-11 18:34 UTC by AzimMuradov

2022-12-12 13:03 UTC, SpirinEgor requested changes
I don't that you need the whole backend with Flask for that app in real life. But why not now, left some comments that might be useful.

2022-12-12 13:19 UTC, AzimMuradov commented on frontend-streamlit/frontend_streamlit/src/main.py
> +    return formatted_question_type
Sadly, I don't know how to do it properly, and I don't think that it's really necessary for one only function.
Also, it may complicate CD

2022-12-12 13:59 UTC, AzimMuradov commented on .github/workflows/backend-ci.yml
> +name: Backend CI
Добавил

2022-12-12 14:02 UTC, AzimMuradov commented on backend/backend/src/api.py
> +            formatted_question_type = "What is _?"
Haha, you are right :sweat_smile:
Just fixed

2022-12-12 14:11 UTC, AzimMuradov commented
I've changed my CD naming + fixed its watch patterns, now it's correct

2022-12-12 14:16 UTC, AzimMuradov commented
> I don't that you need the whole backend with Flask for that app in real life. But why not now, left some comments that might be useful.

I'm going to use it with my telegram bot frontend (WIP)

2022-12-13 12:22 UTC, AzimMuradov commented
Added another frontend (telegram bot). Now I'm going to add missing docs and refactor the code.

2022-12-13 17:39 UTC, AzimMuradov commented
Everything should be fixed :smile:

2022-12-14 15:45 UTC, SpirinEgor commented
Why did you do this in the same PR?.. 48 files changed, it is not that easy to read and check them all...

2022-12-14 15:54 UTC, SpirinEgor approved these changes
Well, for the future stick to the rule: one feature per branch. In real life, nobody will review 50 files per PR 🤷‍♂️

From the application side, it is huge and great work. I really like this 👍 
Tell me about CD, I see prerequisites for it, but there is no action to run it.

2022-12-14 15:55 UTC, merged

2022-12-14 18:42 UTC, AzimMuradov commented
> Why did you do this in the same PR?.. 48 files changed, it is not that easy to read and check them all...

I'm really sorry(
I was afraid that you would not have time to check.
But I understand that this is not an excuse.

2022-12-14 19:09 UTC, AzimMuradov commented
> Tell me about CD, I see prerequisites for it, but there is no action to run it.

https://railway.app takes over the CD

It runs like github action on every push to the `dev` branch (I'm going to change it to `master`)